### ISSUE TITLE
I couldn't find a way to message you in github properly.

### ISSUE THREAD

**Issue by yrkv** [peterje/CommissionCalculator#1]
So should I sign you up for the PSCSTA Programming Contest on 4/20 with me (Yegor Kuznetsov) and Dan Noble?

also, discord tag is `Yegor#0468`

**Comment by yrkv** [comment]
please send me (in discord):
Full Name
Email Address
T-shirt size
Grade
Guardian Name
Guardian Email Address

**Comment by peterje** [comment]
add me back plz
